#!/usr/bin/python3
"""
Defines the class State and an instance Base = declarative_base():
- Use the module SQLAlchemy
- Connect to a MySQL server running on localhost at port 3306
- WARNING: all classes who inherit from Base must be
imported before calling Base.metadata.create_all(engine)
"""

from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class State(Base):
    """
    Contains the class definition of a State
    and an instance Base = declarative_base():
    - inherits from Base
    - links to the MySQL table states
    - class attributes:
    id: column of autogenerated, unique int, can't be null and is a primary key
    name: column of string with maximum 128 chars, can't be null
    """
    __tablename__ = 'states'
    id = Column(Integer, primary_key=True, nullable=False)
    name = Column(String(128), nullable=False)
