#!/usr/bin/python3
"""
Contains the definition of class State and instance Base = declarative_base():
- Use the module SQLAlchemy
- Connect to a MySQL server running on localhost at port 3306
- WARNING: all classes who inherit from Base must be
- imported before calling Base.metadata.create_all(engine)
"""

from sqlalchemy import Column, Integer, String
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from relationship_city import Base, City


class State(Base):
    """
    Contains the class definition of a State
    and an instance Base = declarative_base():
    - inherits from Base
    - links to the MySQL table states
    - class attribute - id: column of autogenerated,
    unique intefer, can't be null and is a primary key
    - class attribute - name: column of string with
    maximum 128 charachters, can't be null
    """
    __tablename__ = 'states'
    id = Column(Integer, primary_key=True, nullable=False)
    name = Column(String(128), nullable=False)
    cities = relationship("City", backref="state")
